version: "3"
services:
  lb:
    image: haproxy
    ports:
      - "3000:3000"
    volumes:
      - ./haproxy:/usr/local/etc/haproxy
  web-app:
    build: ../web-app
    restart: unless-stopped
    ports:
      - "4200:4200"
  rest-api1:
    build: ../rest-api
    restart: unless-stopped
    environment:
      - APPID=API1
    depends_on:
      - core
      - redis
  rest-api2:
    build: ../rest-api
    restart: unless-stopped
    environment:
      - APPID=API2
    depends_on:
      - core
      - redis
  rest-api3:
    build: ../rest-api
    restart: unless-stopped
    environment:
      - APPID=API3
    depends_on:
      - core
      - redis
  redis:
    image: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
  core:
    build: ../core
    restart: unless-stopped
    ports:
      - "3001:3001"
    depends_on:
      - mongo
  mongo:
    image: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
