export enum Commands {
    GET_ALL_PRODUCTS = 'GET_ALL_PRODUCTS',
    GET_PRODUCT = 'GET_PRODUCT',
    CREATE_PRODUCT = 'CREATE_PRODUCT',
    UPDATE_PRODUCT = 'UPDATE_PRODUCT',
    DELETE_PRODUCT = 'DELETE_PRODUCT',
}
